# Generated by Django 4.1 on 2022-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetInfo',
            fields=[
                ('id', models.AutoField(db_column='№', primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(db_column='заказ №')),
                ('cost', models.IntegerField(db_column='стоимость,$')),
                ('delivery_time', models.CharField(db_column='срок поставки', help_text='Expiration date', max_length=10)),
                ('cost_roubles', models.IntegerField(db_column='стоимость,₽')),
            ],
            options={
                'db_table': 'goog_sheet_table',
            },
        ),
    ]
